# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_hospital_facilities_and_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalstaff",
            name="photo_data",
            field=models.TextField(blank=True, default=""),
        ),
    ]
