# Generated by Django 6.0.3 on 2026-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0008_suggestedroute_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='battery_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
